services:
  - type: web
    name: tx-frontend-web
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/your-org/your-repo
    branch: main
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_BASE
        # e.g. https://tx-predictive-intelligence.onrender.com
        value: https://tx-predictive-intelligence.onrender.com
      - key: VITE_SOCKET_BASE
        value: https://tx-predictive-intelligence.onrender.com
      - key: VITE_POLL_INTERVAL_MS
        value: "180000"
      - key: VITE_ENABLE_LOGGING
        value: "true"
